Exposed thing: fixes on Websocket
relu91/thingweb.node-wot pull request #19
Opened 2021-11-26 10:10 UTC by fillobotto

2022-01-28 15:00 UTC, relu91 requested changes
Looks good, I have a concern below.

2022-01-28 15:00 UTC, relu91 commented on packages/binding-websockets/src/ws-server.ts
> +                                .then(() => ws.close(0, "Completed"))
I don't think we need to close the connection after a change is sent to the client. It should be kept open as long as the client likes it.

2022-01-28 15:19 UTC, fillobotto commented on packages/binding-websockets/src/ws-server.ts
> +                                .then(() => ws.close(0, "Completed"))
Instead, I should close the connection here, right? https://github.com/relu91/thingweb.node-wot/blob/b3b5fe7a966b10dcd893a27dca56276c7389c73f/packages/binding-websockets/src/ws-server.ts#L242

2022-01-28 16:20 UTC, relu91 commented on packages/binding-websockets/src/ws-server.ts
> +                                .then(() => ws.close(0, "Completed"))
I think that once you get a close event the ws is already closed by the system. In theory, the server should keep the connection open until it shuts down.

2022-02-08 10:03 UTC, relu91 approved these changes
The last commit looks good, but the PR contains 203 File changes. I'll try to change the target branch to master and see how it works.

2022-02-08 10:08 UTC, fillobotto commented
> The last commit looks good, but the PR contains 203 File changes. I'll try to change the target branch to master and see how it works.

I merged your master branch into my repo because the previous master had some problems with ws tests and that was the result. It's not the first time...any idea of why this keep happening?

2022-02-15 14:24 UTC, relu91 commented
> I merged your master branch into my repo because the previous master had some problems with ws tests and that was the result. It's not the first time...any idea of why this keep happening?

Solved by correctly pointing to the master branch 🥳

2022-02-15 14:25 UTC, merged